# Generated by Django 5.2.8 on 2025-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_address1_alter_customuser_address2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address1",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address2",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="province",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
